apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hnamtrg/22127287-22127370-22127416
    path: petclinic-chart
    targetRevision: feat/ArgoCD
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
      - PrunePropagationPolicy=foreground
