apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hnamtrg/22127287-22127370-22127416
    path: petclinic-chart
    targetRevision: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

